server:
  port: 9001

spring:
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: true
  #  개발용
  datasource:
    url:
    username:
    password:
    driver-class-name:


  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        # table명 대문자로 변환
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true


logging:
  config: classpath:log4j2.xml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
